name: boragapp
description: Borag For Logistical Services.
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.3
  cached_network_image: ^2.5.1
  url_launcher: ^6.0.3
dev_dependencies:
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/imgs/icon.png"
  image_path_android: "assets/imgs/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/fonts/
  fonts:
    - family: Kufi
      fonts:
        - asset: assets/fonts/Kufi-Regular.ttf